Repository Sayak-Karar-2581/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#1 Create twoSum.java
  twoSum.java
Labels: hacktoberfest-accepted, hacktoberfest

#2 Create Bipra.java
  Bipra.java
Labels: hacktoberfest-accepted, hacktoberfest

#3 Create Polymorphism.java
  Polymorphism.java
Labels: hacktoberfest-accepted, hacktoberfest

#7 Create constructor.py
  constructor.py
Labels: hacktoberfest-accepted, hacktoberfest

#6 Updated TwoSum.java
  twoSum.java
Labels: hacktoberfest-accepted, hacktoberfest

#5 Create FloorOfaNum.java
  FloorOfaNum.java
Labels: hacktoberfest-accepted, hacktoberfest

#9 twin_prime
  twin_prime.java
Labels: hacktoberfest-accepted, hacktoberfest

#11 Create maximum minimum consecutive one in c++
  maximum_consecutive_ones.cpp
  non_divisible_subset.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#10 Created LCS in cpp
  longest_common_subsequence.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#12 Create YTDL.py
  YTDL.py
Labels: hacktoberfest-accepted, hacktoberfest

#13 Create radix-sort.java
  radix-sort.java
Labels: hacktoberfest-accepted, hacktoberfest

#16 Create nextGreaterElement.cpp
  dijkstra.cpp
  nextGreaterElement.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#14 Create flood-fill-algo.cpp
  flood-fill-algo.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#19 Create floydWarshall.cpp
  floydWarshall.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#18 Create Bellman-Ford.cpp
  Bellman-Ford.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#23 Create James.py
  James.py
Labels: hacktoberfest-accepted, hacktoberfest

#22 Create stack_span.cpp
  stack_span.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#25 Create Longest palindromic substring.cpp
  Longest Palindromic Substring.cpp
Labels: invalid

#21 Create Basic Arthematic Operation
  Basic Arthematic Operation
Labels: spam

#20 LinearSearch.java
  LinearSearch.java
Labels: spam

#26 Create BLOCKCHAIN.java
  BLOCKCHAIN.java
Labels: hacktoberfest-accepted, hacktoberfest

#28 Create TwoSum.java
  TwoSum.java
Labels: hacktoberfest-accepted, hacktoberfest
